export const SECRET_MANAGER_PRELOADED_DATA_TOKEN = Symbol('SECRET_MANAGER_PRELOADED_DATA_TOKEN')
export const SECRET_MANAGER_CLIENT_TOKEN = Symbol('SECRET_MANAGER_CLIENT_TOKEN')
export const SECRET_MANAGER_OPTIONS = Symbol('SECRET_MANAGER_OPTIONS')
