name: Release package
on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn test
